apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-service
  namespace: urlshortner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-service
  template:
    metadata:
      labels:
        app: node-service
    spec:
      containers:
        - name: node-service
          image: emon110852/urlshortner-node:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "150m"
              memory: "128Mi"
            limits:
              cpu: "750m"
              memory: "512Mi"
          livenessProbe:
            httpGet: { path: "/health", port: 3000 }
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet: { path: "/health", port: 3000 }
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: urlshortner
spec:
  type: ClusterIP
  selector:
    app: node-service
  ports:
    - name: http
      port: 3000
      targetPort: 3000
